[workspace]
members = ["*/"]
exclude = [".git", "target"]

[workspace.package]
license = "MIT"

[workspace.dependencies]
assert_cmd = "2.0.11"
predicates = "3.0.3"
clap = { version = "4.2.7", features = ["derive"] }
simple-eyre = "0.3"
rand = "0.8"
