[package]
name = "echor"
version = "0.1.0"
edition = "2021"
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap.workspace = true

[dev-dependencies]
predicates.workspace = true
assert_cmd.workspace = true
